### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by donjose1000** [Simran9518/Sign-Language-Translator#1]
I have tried to run but its not working in live mode and in localhost also

**Comment by Simran9518** [comment]
Try to install node.js on your system and then start npm to run on local host, the video call function will work fine then. In browser, the video call function is not enabled yet.

**Comment by donjose1000** [comment]
The hosted version is also not working fine. Can't do anything. I think for the hosting part you have not done proper load balancing.

**Comment by Simran9518** [comment]
It's working fine for me, try this https://simran9518.github.io/Sign-Language-Translator/ is this works for you then good or else I think there must be some issue from your end.
